{% set name = "colorhash" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/colorhash-{{ version }}.tar.gz
  sha256: 5460c5539b68712c97b09ba41e5200c81dce6e23f4533d0f4f8beafc3eb2fafa

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - colorhash
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dimostenis/color-hash-python
  summary: Generate color based on any object
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - shaharh9110
